// Set Light Values
#define LED_PIN 26
#define DEFAULT_LIGHT true
#define DEFAULT_BRIGHTNESS 255
#define DEFAULT_SATURATION 0
#define DEFAULT_HUE 255
#define LED_VOLTS 5
#define LED_MAX_AMPS 1500

// LED CONFIG
#define LED_TYPE WS2812
#define NUM_LEDS 36
#define COLOR_ORDER GRB
#define COLOR_TRANSITION_RATE 5
#define COLOR_TRANSITION_DELAY 15
#define DEFAULT_COLOR_PRESET_SETTING false
#define DEFAULT_COLOR_CYCLE_TIME 100
#define BLEND_RATE 5

// Motion Detectors Configuration
#define MOTION_PIN 27
#define DEFAULT_MOTION false
#define DEFAULT_NIGHT_MOTION false
#define DEFAULT_MOTION_AWARENESS_PERIOD 4000
#define MOTION_AWARENESS_COLOR_SHIFT 50
#define NIGHT_MOTION_BRIGHTNESS 100
#define NIGHT_MOTION_TIMEOUT 10000
