// Set Light Values
#define DEFAULT_LIGHT false
#define DEFAULT_BRIGHTNESS 255
#define DEFAULT_SATURATION 0
#define DEFAULT_HUE 255

// LED CONFIG
#define LED_TYPE WS2812
#define NUM_LEDS 28
#define COLOR_ORDER GRB
#define COLOR_TRANSITION_RATE 5
#define COLOR_TRANSITION_DELAY 10